"""add CLI.py

Revision ID: 0299fab53b4e
Revises: 1b3e84ee8440
Create Date: 2025-08-29 21:22:53.800449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0299fab53b4e'
down_revision = '1b3e84ee8440'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
